name: Run lint test and deploy
on: 
  push:
    branches:
      - 'main'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint command
        run: npm run lint
      - name: Run test command
        run: npm run test
      - name: Deploy to external host
        run: echo 'Deploying...'
